version: '3'

services:

  fluent-bit:
    image: fluent/fluent-bit:1.9
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224"
    networks:
      - logging-network

  fluentd:
    build:
      context: ./fluentd
      dockerfile: Dockerfile
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ./logs:/fluentd/log
    ports:
      - "24225:24224"
    networks:
      - logging-network
    user: "root"
    environment:
      - FLUENTD_CONF=fluent.conf
    command: fluentd -c /fluentd/etc/fluent.conf
    depends_on:
      - influxdb

  app:
    build:
      context: ./app
    ports:
      - "3000:3000"
    depends_on:
      - fluent-bit
    networks:
      - logging-network

  influxdb:
    image: influxdb:2.6
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=logging
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-token
    networks:
      - logging-network

networks:
  logging-network:
    driver: bridge

volumes:
  influxdb-data:
